import type { Car, Brand, Testimonial, Stat, NavLink } from '@/types'

export const NAV_LINKS: NavLink[] = [
  { label: 'Collection', href: '#collection' },
  { label: 'Brands', href: '#brands' },
  { label: 'Experience', href: '#experience' },
  { label: 'Clients', href: '#testimonials' },
  { label: 'Contact', href: '#contact' },
]

export const FEATURED_CARS: Car[] = [
  {
    id: 'huracan-sto',
    name: 'Huracán STO',
    brand: 'Lamborghini',
    model: 'Huracán STO',
    year: 2024,
    price: 327838,
    priceDisplay: 'From €327,838',
    specs: {
      power: '640 CV',
      torque: '565 Nm',
      acceleration: '3.0s 0–100',
      topSpeed: '310 km/h',
      engine: 'V10 5.2L Naturally Aspirated',
      transmission: '7-speed DCT',
      drivetrain: 'RWD',
    },
    badge: { text: 'Available Now', variant: 'available' },
    description: 'The Super Trofeo Omologata is pure racing DNA translated for the road. Every gram, every line, every component serves speed.',
    isFeatured: true,
    accentColor: '#C9A84C',
  },
  {
    id: '911-gt3-rs',
    name: '911 GT3 RS',
    brand: 'Porsche',
    model: '911 GT3 RS',
    year: 2024,
    price: 247900,
    priceDisplay: 'From €247,900',
    specs: {
      power: '525 PS',
      torque: '465 Nm',
      acceleration: '3.2s 0–100',
      topSpeed: '296 km/h',
      engine: '4.0L Flat-Six',
      transmission: '7-speed PDK',
      drivetrain: 'RWD',
    },
    badge: { text: 'Pre-Order', variant: 'preorder' },
    description: 'Weissach Package equipped. The most focused GT3 ever built, channeling decades of motorsport mastery.',
    isFeatured: true,
    accentColor: '#7A8FFF',
  },
  {
    id: 'sf90-stradale',
    name: 'SF90 Stradale',
    brand: 'Ferrari',
    model: 'SF90 Stradale',
    year: 2024,
    price: 489000,
    priceDisplay: 'From €489,000',
    specs: {
      power: '1,000 CV',
      torque: '800 Nm',
      acceleration: '2.5s 0–100',
      topSpeed: '340 km/h',
      engine: '4.0L V8 Turbo + 3 Electric Motors',
      transmission: '8-speed DCT',
      drivetrain: 'AWD',
    },
    badge: { text: 'Last Unit', variant: 'last-unit' },
    description: 'Ferrari\'s hybrid pinnacle. One thousand horses bridging combustion and electric in a masterwork of Maranello engineering.',
    isFeatured: true,
    accentColor: '#C0392B',
  },
  {
    id: 'valkyrie-amr',
    name: 'Valkyrie AMR Pro',
    brand: 'Aston Martin',
    model: 'Valkyrie AMR Pro',
    year: 2024,
    price: null,
    priceDisplay: 'POA',
    specs: {
      power: '1,160 BHP',
      acceleration: '<2.5s 0–100',
      topSpeed: '402 km/h+',
      engine: '6.5L Cosworth V12 NA + KERS',
      transmission: '7-speed Ricardo',
    },
    badge: { text: 'In Stock', variant: 'available' },
    description: 'The most powerful naturally aspirated road car ever made. Adrian Newey\'s hypercar vision made devastatingly real.',
    isFeatured: false,
    accentColor: '#6DCC30',
  },
  {
    id: 'chiron-profilee',
    name: 'Chiron Profilee',
    brand: 'Bugatti',
    model: 'Chiron Profilee',
    year: 2024,
    price: 9800000,
    priceDisplay: 'One of One',
    specs: {
      power: '1,600 CV',
      torque: '1,600 Nm',
      acceleration: '2.3s 0–100',
      topSpeed: '420 km/h+',
      engine: '8.0L W16 Quad-Turbo',
      transmission: '7-speed DSG',
      drivetrain: 'AWD',
    },
    badge: { text: 'Bespoke Order', variant: 'bespoke' },
    description: 'The last and most extreme iteration of the Chiron. A singular expression of engineering maximalism — one ever made.',
    isFeatured: false,
    accentColor: '#9B59B6',
  },
]

export const BRANDS: Brand[] = [
  { id: 'ferrari', name: 'Ferrari', country: 'Italy', founded: 1947, speciality: 'Formula One & GT' },
  { id: 'lamborghini', name: 'Lamborghini', country: 'Italy', founded: 1963, speciality: 'Super Sport Cars' },
  { id: 'bugatti', name: 'Bugatti', country: 'France', founded: 1909, speciality: 'Hypercars' },
  { id: 'porsche', name: 'Porsche', country: 'Germany', founded: 1931, speciality: 'Performance GT' },
  { id: 'mclaren', name: 'McLaren', country: 'UK', founded: 1963, speciality: 'Track-focused Supercars' },
  { id: 'aston-martin', name: 'Aston Martin', country: 'UK', founded: 1913, speciality: 'Grand Tourers' },
  { id: 'pagani', name: 'Pagani', country: 'Italy', founded: 1992, speciality: 'Artisanal Hypercars' },
  { id: 'koenigsegg', name: 'Koenigsegg', country: 'Sweden', founded: 1994, speciality: 'Megacar Records' },
  { id: 'rolls-royce', name: 'Rolls-Royce', country: 'UK', founded: 1906, speciality: 'Ultra Luxury' },
  { id: 'bentley', name: 'Bentley', country: 'UK', founded: 1919, speciality: 'Luxury GT' },
  { id: 'maserati', name: 'Maserati', country: 'Italy', founded: 1914, speciality: 'Sport Luxury' },
  { id: 'de-tomaso', name: 'De Tomaso', country: 'Italy', founded: 1959, speciality: 'Italian-American GT' },
]

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 'ar',
    text: 'Velocity Garage didn\'t just sell me a car — they orchestrated the entire experience. From the private viewing to the bespoke configuration session, everything was conducted with a precision and elegance that matched the machine itself.',
    author: {
      name: 'Alessandro Romano',
      initials: 'AR',
      title: 'Chief Investment Officer',
      location: 'Milano',
    },
    rating: 5,
    carPurchased: 'Pagani Huayra BC',
  },
  {
    id: 'sv',
    text: 'Acquiring my Pagani Huayra Roadster through Velocity Garage was an experience beyond any other. Their access to the rarest configurations, their intimate knowledge of each marque, and their discreet white-glove service is simply unmatched.',
    author: {
      name: 'Sofia van der Berg',
      initials: 'SV',
      title: 'Founder, Archipelago Capital',
      location: 'Geneva',
    },
    rating: 5,
    carPurchased: 'Pagani Huayra Roadster',
  },
  {
    id: 'rk',
    text: 'In fifteen years of collecting, I have never encountered a curator with deeper manufacturer relationships. When I requested the one-of-forty Koenigsegg Jesko Absolut, Velocity Garage made the seemingly impossible a reality within six weeks.',
    author: {
      name: 'Ravi Krishnamurthy',
      initials: 'RK',
      title: 'Tech Entrepreneur',
      location: 'Singapore',
    },
    rating: 5,
    carPurchased: 'Koenigsegg Jesko Absolut',
  },
  {
    id: 'jb',
    text: 'The private track day they arranged as part of the delivery experience of my GT3 RS was extraordinary. Three days at Nürburgring with a factory driver alongside. Velocity Garage understands that the vehicle is only the beginning.',
    author: {
      name: 'James Blackwell',
      initials: 'JB',
      title: 'Private Equity Partner',
      location: 'London',
    },
    rating: 5,
    carPurchased: 'Porsche 911 GT3 RS',
  },
]

export const STATS: Stat[] = [
  { value: '847', suffix: '+', label: 'Vehicles Delivered', subLabel: 'to discerning clients worldwide' },
  { value: '32', label: 'Exclusive Marques', subLabel: 'in our curated portfolio' },
  { value: '€2.4', suffix: 'B', label: 'Total Value Traded', subLabel: 'across 15 years of operation' },
  { value: '98', suffix: '%', label: 'Client Retention', subLabel: 'across our entire history' },
]

export const HERO_STATS = [
  { num: 847, label: 'Vehicles Delivered' },
  { num: 32, label: 'Exclusive Marques' },
  { num: 15, label: 'Years of Excellence' },
  { num: 98, label: 'Client Satisfaction %' },
]
