# ─── Stage 1: Dependencies ────────────────────────────────────────────
FROM node:20-alpine AS deps

# libc6-compat needed for some native npm packages on Alpine
RUN apk add --no-cache libc6-compat

WORKDIR /app

# Copy only lockfiles first — maximises Docker layer cache reuse.
# This layer only re-runs when package.json / lockfile changes.
COPY package.json package-lock.json* ./

RUN npm install

# ─── Stage 2: Builder ─────────────────────────────────────────────────
FROM node:20-alpine AS builder

WORKDIR /app

# Bring in installed node_modules from deps stage
COPY --from=deps /app/node_modules ./node_modules

# Copy all source files
COPY . .

# Disable telemetry — no network calls during CI build
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

# Build produces:
#   .next/standalone/   ← self-contained Node server (needs output:'standalone')
#   .next/static/       ← hashed static assets
#   public/             ← copied as-is
RUN npm run build

# ─── Stage 3: Runner (minimal production image) ───────────────────────
FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"

# Create a non-root user — never run production as root
RUN addgroup --system --gid 1001 nodejs && \
    adduser  --system --uid 1001 nextjs

# ── Copy public assets ──────────────────────────────────────────────
# public/ must exist in the repo (even if empty — add a .gitkeep).
# Docker COPY fails silently on missing source only with wildcards;
# a direct path like /app/public will error if missing — intentional.
COPY --from=builder /app/public ./public

# ── Prerender cache directory ───────────────────────────────────────
RUN mkdir -p .next && chown nextjs:nodejs .next

# ── Standalone server bundle ────────────────────────────────────────
# .next/standalone/ is only produced when next.config.ts has:
#   output: 'standalone'
# It contains server.js + all required node_modules (tree-shaken).
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./

# ── Static assets ───────────────────────────────────────────────────
# Must be copied separately into the standalone directory structure.
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

# server.js is the entrypoint generated by Next.js standalone output
CMD ["node", "server.js"]
